name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-discord-python:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.9
      with:
        python-version: "3.9.9"
    - name: Install Library
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python
      run: |
        python src/main.py
