name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    environment: "GCP: Free Plan Project Environment"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

    - id: 'google-cloud-auth'
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v0.7.0'
      with:
        create_credentials_file: true
        workload_identity_provider: 'projects/${{secrets.YOUR_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/${{secrets.YOUR_POOL_ID}}/providers/${{secrets.YOUR_PROVIDER_ID}}'
        service_account: ${{secrets.SERVICE_ACCOUNT_NAME}}@${{secrets.PROJECT_NAME}}.iam.gserviceaccount.com

    - name: Google Cloud login
      run: |
        cat ${{ steps.google-cloud-auth.outputs.credentials_file_path }}
        gcloud auth login --brief --cred-file="${{ steps.google-cloud-auth.outputs.credentials_file_path }}"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
        cd Discord-RKS-Bot
        git pull
        source restart_daemon.sh

  # run-discord-python:

  #   runs-on: ubuntu-latest
    
  #   env:
  #     TOKEN: ${{secrets.TOKEN}}
  #     TEST: ${{secrets.TEST}}

    # steps:
    # - uses: actions/checkout@v3
    # - name: Set up Python 3.8
    #   uses: actions/setup-python@v3
    #   with:
    #       python-version: '3.8'
    #       architecture: 'x64'
    # - name: Get Python version
    #   run: |
    #     python -V
    #     echo ${{secrets.TOKEN}}
    # - name: Install Library
    #   run: |
    #     pip install -r requirements.txt
    # - name: Run Python
    #   run: |
    #     python src/main.py
